- .github/workflows/chart-release.yml
- charts/orchestrator/Chart.yaml
Updated the helm chart version
> Release chart for autosetup

- CHANGELOG.md
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- src/main/java/org/eclipse/tractusx/autosetup/manager/TractusConnectorManager.java
- src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java
- src/main/java/org/eclipse/tractusx/autosetup/service/EDCConnectorWorkFlow.java
- src/main/resources/flyway/V4__rename-tractus-connector.sql
Fixed email sent issue for failure use case of connector test
Rename tractus-X connector app name because of ingress access issue
> Release1.2.3

- CHANGELOG.md
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/values.yaml
- pom.xml
Changed default ingress to false
> Qualitygate

- CHANGELOG.md
- DEPENDENCIES
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- pom.xml
- src/main/java/org/eclipse/tractusx/autosetup/manager/ConnectorRegistrationManager.java
- src/test/java/org/eclipse/tractusx/autosetup/manager/ConnectorRegistrationManagerTest.java
- Please first merge PR# https://github.com/eclipse-tractusx/managed-service-orchestrator/pull/39
- Veracode issue fix by upgrading spring boot version
> fix: _Upgrade spring boot version_

- .github/workflows/trivy.yml
- CHANGELOG.md
- README.md
- charts/chart-testing-config.yaml
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- pom.xml
- src/main/java/org/eclipse/tractusx/autosetup/config/EclipseLinkJpaConfiguration.java
- src/main/java/org/eclipse/tractusx/autosetup/entity/AutoSetupTriggerEntry.java
- src/main/java/org/eclipse/tractusx/autosetup/manager/ConnectorRegistrationManager.java
- src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java
- src/main/java/org/eclipse/tractusx/autosetup/service/DTAppWorkFlow.java
- src/main/resources/templates/success.html
- This PR contains change related to email notification
> feat: _Email notification_

- .github/workflows/build.yaml
- .github/workflows/trivy.yml
- CHANGELOG.md
- DEPENDENCIES
- README.md
- charts/chart-testing-config.yaml
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- charts/orchestrator/values.yaml
- pom.xml
- src/main/java/org/eclipse/tractusx/autosetup/config/EclipseLinkJpaConfiguration.java
- src/main/java/org/eclipse/tractusx/autosetup/entity/AutoSetupTriggerEntry.java
- src/main/java/org/eclipse/tractusx/autosetup/manager/ConnectorRegistrationManager.java
- src/main/java/org/eclipse/tractusx/autosetup/service/AutoSetupOrchitestratorService.java
- src/main/java/org/eclipse/tractusx/autosetup/service/DTAppWorkFlow.java
- src/main/resources/templates/success.html
- This PR consist of Trivy/veracode security issue fixed
- First merge PR #57
> fix: _security issue hot fix_

- CHANGELOG.md
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- docs/autosetup-api.yaml
- pom.xml
> fix: _Updated product name_

- .github/workflows/helm-lint.yaml
- CHANGELOG.md
- Dockerfile
- README.md
- SECURITY.md
- charts/orchestrator/README.md
- charts/orchestrator/templates/NOTES.txt
- charts/orchestrator/templates/_helpers.tpl
- charts/orchestrator/templates/deployment.yaml
- charts/orchestrator/templates/hpa.yaml
- charts/orchestrator/templates/ingress.yaml
- charts/orchestrator/templates/service.yaml
- charts/orchestrator/templates/serviceaccount.yaml
- charts/orchestrator/templates/tests/test-connection.yaml
- charts/orchestrator/values.yaml
- docs/ARC42.md
- pom.xml
- Fixes the QG issues
- Fixes #66 
- Fixes #67
> fix: _Quality gate checks_

- CHANGELOG.md
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/values.yaml
- pom.xml
- src/main/java/org/eclipse/tractusx/autosetup/apiproxy/EDCApiProxy.java
- src/main/java/org/eclipse/tractusx/autosetup/apiproxy/EDCProxyService.java
- src/main/java/org/eclipse/tractusx/autosetup/manager/DTRegistryManager.java
- src/main/java/org/eclipse/tractusx/autosetup/manager/VaultManager.java
- src/main/resources/edc-request-template/asset-request-filter.json
- src/main/resources/edc-request-template/asset.json
- src/main/resources/edc-request-template/contract-defination.json
- src/main/resources/edc-request-template/policy.json
- This PR consist of changes related to updation of DT asset creation for oauth secret information
> feat: Update DT asset creation 

- CHANGELOG.md
- INSTALL.md
> fix: Updation in installation steps

- CHANGELOG.md
- README.md
> fix: Updated Readme file

- .github/workflows/helm-lint.yaml
- Fixes #93 
- This PR consist of adding the version with which it is upgraded from and test it
> fix: TRG 5.11 Chart upgrading test

- .github/workflows/helm-lint.yaml
- Fixes #93 
- Updating name of published repo in helm lint workflow file
> fix: Updating published repo name

- .github/workflows/helm-lint.yaml
Updated the last version number
> fix: Updated version number

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- Security issue CVE-2023-34053(denial of service)
- Security issue CVE-2023-46589(HTTP request smuggling via malformed trailer headers)
- Security issue CVE-2023-6378(serialization vulnerability in logback)
> [Fix|MSO] Fixed trivy security issues. 

- CHANGELOG.md
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- pom.xml
- As we have fixed all the vulnerabilities. This PR is to change the version and create new release.
> docs: creation of new release

- .tractusx
- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- Security issue CVE-2024-1597(postgresql vulnerable to SQL Injection)
- Security issue CVE-2024-22234(Broken Access Control in Spring Security)
> [Fix|MSO] Fixed security vulnerability issues.

- DOCKER_NOTICE.md
- README.md
- Resolves #106 
- Created separate file for "Notice for Docker image" section.
> docs: Addition of docker notice

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- libraries update
- to fix CVE-2024-22234 and CVE-2024-22243
- to have up-to-date libraries in project
> update Spring Boot to 3.2.3

- .github/workflows/codeql.yml
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- This PR is for addition of new workflow called as codeQL
- It is used for code scanning to find security vulnerabilities and errors in the code.
> chore: Addition of codeQL workflow

- .github/workflows/trivy.yml
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
-There are minor changes in the workflow such as severity, exit code.
> chore: Modification in trivy workflow

- .github/workflows/build.yaml
- .github/workflows/codeql.yml
- .github/workflows/helm-lint.yaml
- .github/workflows/kics.yml
- .github/workflows/trivy.yml
- This PR have the upgraded action versions of workflow
> chore: Updated version according to dependabot

- CHANGELOG.md
- DEPENDENCIES
- pom.xml
- Dependabot bump version fixes
> [Fix|MSO] : Dependabot reported security issues fixed

- Dockerfile
- This PR consist of changes regarding to legal distribution info in Dockerfile
-  Resolves #150 
- Resolves #165 
> chore: Updated legal distribution information

- README.md
- This PR has the description of health check URL
> docs: Updated health check url

- CONTRIBUTING.md
- LICENSE_non-code
- NOTICE.md
This PR contains the changes w.r.t TRG 7.07, TRG7.08
> docs: Update legal notice

- .github/workflows/trivy.yml
> fix: trivy workflow fix

- CHANGELOG.md
- README.md
- charts/orchestrator/Chart.yaml
- charts/orchestrator/README.md
- pom.xml
- This PR is to create new build version with app 1.5.7
> build: create new build version 1.5.7
